(()=>{
  const form=document.getElementById('vyraInquiryForm');
  const bookingUrl='https://calendar.app.google/iarNpo68qgn3ZdXP8';
  if(form){
    const submit=form.querySelector('button[type="submit"]'),formCard=document.getElementById('inquiryFormCard');let sending=false;
    let status=document.getElementById('inquiryStatus');if(!status){status=document.createElement('div');status.id='inquiryStatus';status.style.cssText='margin-top:12px;font-size:13px;line-height:1.5';form.appendChild(status)}
    let success=document.getElementById('inquirySuccess');if(!success&&formCard){success=document.createElement('div');success.id='inquirySuccess';success.hidden=true;success.style.cssText='padding:34px;border:1px solid rgba(255,255,255,.18);border-radius:18px;text-align:center;background:rgba(255,255,255,.035)';success.innerHTML='<span class="section-kicker">INQUIRY RECEIVED ✓</span><h3 style="font-size:30px;margin:10px 0">Thank you, <span id="successFirstName">THERE</span>!</h3><p style="max-width:620px;margin:0 auto">Your inquiry has been sent to VYRA Collective. Our team will review your project details and get back to you soon.</p><button class="btn btn-ghost" id="sendAnotherInquiry" type="button" style="margin-top:22px">SEND ANOTHER INQUIRY</button>';formCard.insertAdjacentElement('afterend',success);success.querySelector('#sendAnotherInquiry').onclick=()=>{success.hidden=true;formCard.hidden=false;formCard.scrollIntoView({behavior:'smooth',block:'center'})}}
    form.addEventListener('submit',async e=>{e.preventDefault();if(sending||!form.reportValidity())return;sending=true;if(submit){submit.disabled=true;submit.textContent='SENDING...'}status.textContent='Sending your inquiry…';status.style.color='';try{const fd=new FormData(form);const r=await fetch(form.action,{method:'POST',body:fd,headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Inquiry delivery failed');const name=String(fd.get('full_name')||'').trim();const first=document.getElementById('successFirstName');if(first)first.textContent=(name.split(/\s+/)[0]||'THERE').toUpperCase();form.reset();formCard.hidden=true;success.hidden=false;success.scrollIntoView({behavior:'smooth',block:'center'});}catch(err){console.error('VYRA inquiry error:',err);status.textContent='We couldn’t send your inquiry. Please try again.';status.style.color='#ffd4d4'}finally{sending=false;if(submit){submit.disabled=false;submit.textContent='Send Inquiry'}}});
  }
  function openDiscovery(e){e?.preventDefault();let modal=document.getElementById('vyraDiscoveryModal');if(!modal){modal=document.createElement('div');modal.id='vyraDiscoveryModal';modal.innerHTML='<div class="vyra-booking-shell"><div class="vyra-booking-head"><div><span>VYRA COLLECTIVE</span><h2>Book a Discovery Call</h2><p>Select an available date and time below.</p></div><button type="button" class="vyra-booking-close" aria-label="Close">×</button></div><div class="vyra-booking-frame"><iframe src="'+bookingUrl+'" title="VYRA Discovery Call booking" loading="lazy" allow="clipboard-write"></iframe></div></div>';document.body.appendChild(modal);modal.querySelector('.vyra-booking-close').onclick=()=>{modal.classList.remove('open');document.body.style.overflow=''};modal.onclick=x=>{if(x.target===modal){modal.classList.remove('open');document.body.style.overflow=''}}}modal.classList.add('open');document.body.style.overflow='hidden'}
  function addDiscoveryButtons(){const nav=document.querySelector('.site-header .nav');if(nav&&!nav.querySelector('.discovery-call-link')){const inquiry=nav.querySelector('a[href="#inquiry"]');const a=document.createElement('a');a.href='#discovery-call';a.className='btn btn-small discovery-call-link';a.textContent='Discovery Call';a.onclick=openDiscovery;if(inquiry)inquiry.insertAdjacentElement('afterend',a);else nav.appendChild(a)}const actions=document.querySelector('.hero-actions');if(actions&&!actions.querySelector('.discovery-call-hero')){const inquiry=actions.querySelector('a[href="#inquiry"]');const a=document.createElement('a');a.href='#discovery-call';a.className='btn discovery-call-hero';a.textContent='Discovery Call';a.onclick=openDiscovery;if(inquiry)inquiry.insertAdjacentElement('afterend',a);else actions.prepend(a)}const progress=document.querySelector('.inquiry-progress');if(progress)progress.innerHTML='<span class="active">PROJECT INQUIRY</span>'}
  addDiscoveryButtons();
  const nav=document.querySelector('.site-header .nav');if(nav&&!nav.querySelector('.employee-login-link')){const link=document.createElement('a');link.href='employee-login.html';link.className='employee-login-link';link.textContent='Employee Login';const inquiry=nav.querySelector('a[href="#inquiry"]');inquiry?nav.insertBefore(link,inquiry):nav.appendChild(link);link.addEventListener('click',()=>nav.classList.remove('open'))}
  const style=document.createElement('style');style.textContent='.employee-login-link{display:inline-flex!important;align-items:center;justify-content:center;gap:7px;padding:9px 14px!important;border:1px solid rgba(255,255,255,.28);border-radius:999px;text-decoration:none;white-space:nowrap;font-size:12px!important;font-weight:800!important;letter-spacing:.04em;transition:.2s ease}.employee-login-link:before{content:"🔒";font-size:11px}.employee-login-link:hover{background:rgba(255,255,255,.1);transform:translateY(-1px)}.site-header .nav .discovery-call-link{margin-left:6px}.hero-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.hero-actions>a.btn{min-width:190px;min-height:52px;box-sizing:border-box;display:inline-flex;align-items:center;justify-content:center;text-align:center}.hero-actions .discovery-call-hero{background:#d7b866!important;color:#08172f!important;border-color:#d7b866!important;border-radius:999px!important}#vyraDiscoveryModal{position:fixed;inset:0;z-index:100000;background:rgba(3,12,29,.88);backdrop-filter:blur(10px);display:none;padding:24px;overflow:auto}#vyraDiscoveryModal.open{display:flex;align-items:center;justify-content:center}.vyra-booking-shell{width:min(1100px,100%);height:min(850px,92vh);background:#0b1b3d;border:1px solid rgba(215,184,102,.4);border-radius:24px;overflow:hidden;box-shadow:0 30px 90px #0009;display:flex;flex-direction:column}.vyra-booking-head{padding:22px 26px;display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid rgba(255,255,255,.12);color:#fff}.vyra-booking-head span{font-size:11px;letter-spacing:.18em;color:#d7b866;font-weight:800}.vyra-booking-head h2{margin:5px 0 2px;font-size:26px}.vyra-booking-head p{margin:0;color:rgba(255,255,255,.68);font-size:13px}.vyra-booking-close{width:44px;height:44px;border-radius:50%;border:1px solid rgba(255,255,255,.22);background:transparent;color:#fff;font-size:27px;cursor:pointer}.vyra-booking-frame{flex:1;background:#fff;min-height:0}.vyra-booking-frame iframe{width:100%;height:100%;border:0;background:#fff}@media(max-width:650px){#vyraDiscoveryModal{padding:8px}.vyra-booking-shell{height:96vh;border-radius:16px}.vyra-booking-head{padding:16px}.vyra-booking-head h2{font-size:21px}}';document.head.appendChild(style);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){const m=document.getElementById('vyraDiscoveryModal');if(m?.classList.contains('open')){m.classList.remove('open');document.body.style.overflow=''}}});
})();