(()=>{
  const form=document.getElementById('vyraInquiryForm');
  if(form){
    const submit=form.querySelector('button[type="submit"]'),formCard=document.getElementById('inquiryFormCard');
    const inquiryApi='https://ptzurrebwksuvuakgvym.supabase.co/functions/v1/website-inquiry';
    const bookingUrl='https://calendar.app.google/iarNpo68qgn3ZdXP8';let sending=false;
    let status=document.getElementById('inquiryStatus');if(!status){status=document.createElement('div');status.id='inquiryStatus';status.style.cssText='margin-top:12px;font-size:13px;line-height:1.5';form.appendChild(status)}
    let success=document.getElementById('inquirySuccess');if(!success&&formCard){success=document.createElement('div');success.id='inquirySuccess';success.hidden=true;success.style.cssText='padding:34px;border:1px solid rgba(255,255,255,.18);border-radius:18px;text-align:center;background:rgba(255,255,255,.035)';success.innerHTML='<span class="section-kicker">01 INQUIRY RECEIVED ✓</span><h3 style="font-size:30px;margin:10px 0">Thank you, <span id="successFirstName">THERE</span>!</h3><p style="max-width:620px;margin:0 auto 26px">Your inquiry has been received. The next step is to schedule your Discovery Call with Katherine.</p><div style="height:1px;background:rgba(255,255,255,.14);margin:24px 0"></div><span class="section-kicker">02 DISCOVERY CALL</span><h3 style="font-size:28px;margin:10px 0">Choose a date and time that works for you.</h3><p style="max-width:620px;margin:0 auto 22px">Open the VYRA Google Calendar booking page and select an available schedule for your Discovery Call.</p><a class="btn" href="'+bookingUrl+'" target="_blank" rel="noopener">BOOK YOUR DISCOVERY CALL →</a>';formCard.insertAdjacentElement('afterend',success)}
    form.addEventListener('submit',async e=>{e.preventDefault();if(sending||!form.reportValidity())return;sending=true;if(submit){submit.disabled=true;submit.textContent='SENDING...'}status.textContent='Saving your inquiry…';status.style.color='';try{const fd=new FormData(form);const payload={full_name:String(fd.get('full_name')||''),email:String(fd.get('email')||''),company:String(fd.get('company')||''),website:String(fd.get('website')||''),services:fd.getAll('services').map(String),budget:String(fd.get('budget')||''),message:String(fd.get('message')||''),goals:String(fd.get('message')||'')};
      const db=await fetch(inquiryApi,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let dj={};try{dj=await db.json()}catch(_){}if(!db.ok||!dj.ok)throw new Error(dj.error||'Could not save inquiry to VYRA system');
      fetch(form.action,{method:'POST',body:fd,headers:{Accept:'application/json'}}).catch(()=>{});
      const first=document.getElementById('successFirstName');if(first)first.textContent=(payload.full_name.trim().split(/\s+/)[0]||'THERE').toUpperCase();form.reset();formCard.hidden=true;success.hidden=false;success.scrollIntoView({behavior:'smooth',block:'center'});
    }catch(err){console.error('VYRA inquiry error:',err);status.textContent='We couldn’t save your inquiry to the VYRA system. Please try again.';status.style.color='#ffd4d4'}finally{sending=false;if(submit){submit.disabled=false;submit.textContent='Send Inquiry'}}});
  }
  const nav=document.querySelector('.site-header .nav');if(nav&&!nav.querySelector('.employee-login-link')){const link=document.createElement('a');link.href='employee-login.html';link.className='employee-login-link';link.textContent='Employee Login';const cta=nav.querySelector('a[href="#inquiry"]');cta?nav.insertBefore(link,cta):nav.appendChild(link);link.addEventListener('click',()=>nav.classList.remove('open'));const style=document.createElement('style');style.textContent='.employee-login-link{display:inline-flex!important;align-items:center;justify-content:center;gap:7px;padding:9px 14px!important;border:1px solid rgba(255,255,255,.28);border-radius:999px;text-decoration:none;white-space:nowrap;font-size:12px!important;font-weight:800!important;letter-spacing:.04em;transition:.2s ease}.employee-login-link:before{content:"🔒";font-size:11px}.employee-login-link:hover{background:rgba(255,255,255,.1);transform:translateY(-1px)}';document.head.appendChild(style)}
})();