(()=>{
const baseVerses=[
['Commit thy works unto the LORD, and thy thoughts shall be established.','Proverbs 16:3'],
['And whatsoever ye do, do it heartily, as to the Lord, and not unto men.','Colossians 3:23'],
['Be strong and of a good courage; be not afraid... for the LORD thy God is with thee whithersoever thou goest.','Joshua 1:9'],
['Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.','Psalm 37:5'],
['Trust in the LORD with all thine heart; and lean not unto thine own understanding.','Proverbs 3:5'],
['In all thy ways acknowledge him, and he shall direct thy paths.','Proverbs 3:6'],
['I can do all things through Christ which strengtheneth me.','Philippians 4:13'],
['But they that wait upon the LORD shall renew their strength.','Isaiah 40:31'],
['For with God nothing shall be impossible.','Luke 1:37'],
['Let all your things be done with charity.','1 Corinthians 16:14'],
['Whatsoever thy hand findeth to do, do it with thy might.','Ecclesiastes 9:10'],
['The LORD is my strength and my shield; my heart trusted in him, and I am helped.','Psalm 28:7'],
['This is the day which the LORD hath made; we will rejoice and be glad in it.','Psalm 118:24'],
['The steps of a good man are ordered by the LORD: and he delighteth in his way.','Psalm 37:23'],
['The fear of the LORD is the beginning of wisdom.','Proverbs 9:10'],
['A man’s heart deviseth his way: but the LORD directeth his steps.','Proverbs 16:9'],
['The name of the LORD is a strong tower: the righteous runneth into it, and is safe.','Proverbs 18:10'],
['Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.','Proverbs 27:17'],
['Where there is no vision, the people perish.','Proverbs 29:18'],
['Wait on the LORD: be of good courage, and he shall strengthen thine heart.','Psalm 27:14'],
['Delight thyself also in the LORD; and he shall give thee the desires of thine heart.','Psalm 37:4'],
['God is our refuge and strength, a very present help in trouble.','Psalm 46:1'],
['Be still, and know that I am God.','Psalm 46:10'],
['Create in me a clean heart, O God; and renew a right spirit within me.','Psalm 51:10'],
['Cast thy burden upon the LORD, and he shall sustain thee.','Psalm 55:22'],
['For the LORD God is a sun and shield... no good thing will he withhold from them that walk uprightly.','Psalm 84:11'],
['Thy word is a lamp unto my feet, and a light unto my path.','Psalm 119:105'],
['They that sow in tears shall reap in joy.','Psalm 126:5'],
['Search me, O God, and know my heart... and lead me in the way everlasting.','Psalm 139:23–24'],
['The joy of the LORD is your strength.','Nehemiah 8:10'],
['For we are labourers together with God.','1 Corinthians 3:9'],
['Let all things be done decently and in order.','1 Corinthians 14:40'],
['Watch ye, stand fast in the faith, quit you like men, be strong.','1 Corinthians 16:13'],
['For we walk by faith, not by sight.','2 Corinthians 5:7'],
['My grace is sufficient for thee: for my strength is made perfect in weakness.','2 Corinthians 12:9'],
['Let us not be weary in well doing: for in due season we shall reap, if we faint not.','Galatians 6:9'],
['With all lowliness and meekness, with longsuffering, forbearing one another in love.','Ephesians 4:2'],
['Be ye kind one to another, tenderhearted, forgiving one another.','Ephesians 4:32'],
['Redeeming the time, because the days are evil.','Ephesians 5:16'],
['Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.','Philippians 4:6'],
['And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.','Philippians 4:7'],
['Whatsoever things are true... honest... just... pure... lovely... think on these things.','Philippians 4:8'],
['Let your speech be alway with grace, seasoned with salt.','Colossians 4:6'],
['Rejoice evermore. Pray without ceasing. In every thing give thanks.','1 Thessalonians 5:16–18'],
['For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.','2 Timothy 1:7'],
['Let us run with patience the race that is set before us.','Hebrews 12:1'],
['If any of you lack wisdom, let him ask of God... and it shall be given him.','James 1:5'],
['Every good gift and every perfect gift is from above.','James 1:17'],
['Faith, if it hath not works, is dead, being alone.','James 2:17'],
['Humble yourselves in the sight of the Lord, and he shall lift you up.','James 4:10'],
['Casting all your care upon him; for he careth for you.','1 Peter 5:7'],
['And above all things have fervent charity among yourselves.','1 Peter 4:8'],
['As every man hath received the gift, even so minister the same one to another.','1 Peter 4:10'],
['Greater is he that is in you, than he that is in the world.','1 John 4:4'],
['We love him, because he first loved us.','1 John 4:19'],
['Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.','Matthew 7:7'],
['Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.','Matthew 5:16'],
['Seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.','Matthew 6:33'],
['With God all things are possible.','Matthew 19:26'],
['Whosoever will be chief among you, let him be your servant.','Matthew 20:27'],
['Love thy neighbour as thyself.','Matthew 22:39'],
['All things, whatsoever ye shall ask in prayer, believing, ye shall receive.','Matthew 21:22'],
['He that is faithful in that which is least is faithful also in much.','Luke 16:10'],
['Give, and it shall be given unto you.','Luke 6:38'],
['Peace I leave with you, my peace I give unto you.','John 14:27'],
['Abide in me, and I in you.','John 15:4'],
['Herein is my Father glorified, that ye bear much fruit.','John 15:8'],
['These things I have spoken unto you, that in me ye might have peace.','John 16:33'],
['If God be for us, who can be against us?','Romans 8:31'],
['And we know that all things work together for good to them that love God.','Romans 8:28'],
['Be not overcome of evil, but overcome evil with good.','Romans 12:21'],
['Be kindly affectioned one to another with brotherly love; in honour preferring one another.','Romans 12:10'],
['Not slothful in business; fervent in spirit; serving the Lord.','Romans 12:11'],
['Rejoicing in hope; patient in tribulation; continuing instant in prayer.','Romans 12:12'],
['Let us therefore follow after the things which make for peace, and things wherewith one may edify another.','Romans 14:19'],
['We then that are strong ought to bear the infirmities of the weak, and not to please ourselves.','Romans 15:1'],
['The God of hope fill you with all joy and peace in believing.','Romans 15:13'],
['Behold, how good and how pleasant it is for brethren to dwell together in unity!','Psalm 133:1'],
['Except the LORD build the house, they labour in vain that build it.','Psalm 127:1'],
['Teach us to number our days, that we may apply our hearts unto wisdom.','Psalm 90:12'],
['O satisfy us early with thy mercy; that we may rejoice and be glad all our days.','Psalm 90:14'],
['He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.','Psalm 91:1'],
['It is a good thing to give thanks unto the LORD.','Psalm 92:1'],
['O come, let us sing unto the LORD: let us make a joyful noise to the rock of our salvation.','Psalm 95:1'],
['Serve the LORD with gladness: come before his presence with singing.','Psalm 100:2'],
['Bless the LORD, O my soul, and forget not all his benefits.','Psalm 103:2'],
['O give thanks unto the LORD; for he is good: for his mercy endureth for ever.','Psalm 107:1'],
['The LORD is on my side; I will not fear.','Psalm 118:6'],
['Open thou mine eyes, that I may behold wondrous things out of thy law.','Psalm 119:18'],
['Great peace have they which love thy law.','Psalm 119:165'],
['I will lift up mine eyes unto the hills, from whence cometh my help.','Psalm 121:1'],
['My help cometh from the LORD, which made heaven and earth.','Psalm 121:2'],
['The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore.','Psalm 121:8'],
['They that trust in the LORD shall be as mount Zion, which cannot be removed.','Psalm 125:1'],
['The LORD hath done great things for us; whereof we are glad.','Psalm 126:3'],
['I will praise thee; for I am fearfully and wonderfully made.','Psalm 139:14'],
['Cause me to hear thy lovingkindness in the morning... cause me to know the way wherein I should walk.','Psalm 143:8'],
['The LORD is gracious, and full of compassion; slow to anger, and of great mercy.','Psalm 145:8'],
['The LORD is nigh unto all them that call upon him.','Psalm 145:18'],
['He healeth the broken in heart, and bindeth up their wounds.','Psalm 147:3'],
['The LORD giveth wisdom: out of his mouth cometh knowledge and understanding.','Proverbs 2:6'],
['Keep thy heart with all diligence; for out of it are the issues of life.','Proverbs 4:23'],
['Go to the ant... consider her ways, and be wise.','Proverbs 6:6'],
['Hatred stirreth up strifes: but love covereth all sins.','Proverbs 10:12'],
['Where no counsel is, the people fall: but in the multitude of counsellors there is safety.','Proverbs 11:14'],
['A generous person shall prosper; and he that watereth shall be watered also himself.','Proverbs 11:25'],
['The way of a fool is right in his own eyes: but he that hearkeneth unto counsel is wise.','Proverbs 12:15'],
['A soft answer turneth away wrath.','Proverbs 15:1'],
['Without counsel purposes are disappointed: but in the multitude of counsellors they are established.','Proverbs 15:22'],
['Pleasant words are as an honeycomb, sweet to the soul, and health to the bones.','Proverbs 16:24'],
['He that hath knowledge spareth his words.','Proverbs 17:27'],
['A man’s gift maketh room for him, and bringeth him before great men.','Proverbs 18:16'],
['Many are the plans in a man’s heart; nevertheless the counsel of the LORD, that shall stand.','Proverbs 19:21'],
['The just man walketh in his integrity: his children are blessed after him.','Proverbs 20:7'],
['To do justice and judgment is more acceptable to the LORD than sacrifice.','Proverbs 21:3'],
['A good name is rather to be chosen than great riches.','Proverbs 22:1'],
['Seest thou a man diligent in his business? he shall stand before kings.','Proverbs 22:29'],
['Faithful are the wounds of a friend.','Proverbs 27:6'],
['The wicked flee when no man pursueth: but the righteous are bold as a lion.','Proverbs 28:1'],
['He that trusteth in the LORD shall be made fat.','Proverbs 28:25'],
['Two are better than one; because they have a good reward for their labour.','Ecclesiastes 4:9'],
['To every thing there is a season, and a time to every purpose under the heaven.','Ecclesiastes 3:1'],
['Cast thy bread upon the waters: for thou shalt find it after many days.','Ecclesiastes 11:1'],
['They that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.','Isaiah 40:31'],
['Fear thou not; for I am with thee: be not dismayed; for I am thy God.','Isaiah 41:10'],
['When thou passest through the waters, I will be with thee.','Isaiah 43:2'],
['Behold, I will do a new thing; now it shall spring forth.','Isaiah 43:19'],
['Thou wilt keep him in perfect peace, whose mind is stayed on thee.','Isaiah 26:3'],
['In quietness and in confidence shall be your strength.','Isaiah 30:15'],
['And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it.','Isaiah 30:21'],
['No weapon that is formed against thee shall prosper.','Isaiah 54:17'],
['Arise, shine; for thy light is come, and the glory of the LORD is risen upon thee.','Isaiah 60:1'],
['The LORD’s mercies... are new every morning: great is thy faithfulness.','Lamentations 3:22–23'],
['It is good that a man should both hope and quietly wait for the salvation of the LORD.','Lamentations 3:26'],
['For I know the thoughts that I think toward you, saith the LORD, thoughts of peace.','Jeremiah 29:11'],
['Call unto me, and I will answer thee, and shew thee great and mighty things.','Jeremiah 33:3'],
['Blessed is the man that trusteth in the LORD, and whose hope the LORD is.','Jeremiah 17:7'],
['I will give them one heart, and one way, that they may fear me for ever.','Jeremiah 32:39'],
['He hath shewed thee, O man, what is good... to do justly, and to love mercy, and to walk humbly with thy God.','Micah 6:8'],
['The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.','Nahum 1:7'],
['Not by might, nor by power, but by my spirit, saith the LORD of hosts.','Zechariah 4:6'],
['Prove me now herewith, saith the LORD of hosts... if I will not open you the windows of heaven.','Malachi 3:10'],
['Blessed are the peacemakers: for they shall be called the children of God.','Matthew 5:9'],
['Blessed are the pure in heart: for they shall see God.','Matthew 5:8'],
['Where your treasure is, there will your heart be also.','Matthew 6:21'],
['Take therefore no thought for the morrow.','Matthew 6:34'],
['Therefore all things whatsoever ye would that men should do to you, do ye even so to them.','Matthew 7:12'],
['Come unto me, all ye that labour and are heavy laden, and I will give you rest.','Matthew 11:28'],
['Learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.','Matthew 11:29'],
['He that is greatest among you shall be your servant.','Matthew 23:11'],
['Watch and pray, that ye enter not into temptation.','Matthew 26:41'],
['Go ye therefore, and teach all nations.','Matthew 28:19'],
['With men it is impossible, but not with God: for with God all things are possible.','Mark 10:27'],
['Whosoever will be great among you, shall be your minister.','Mark 10:43'],
['Have faith in God.','Mark 11:22'],
['What things soever ye desire, when ye pray, believe that ye receive them.','Mark 11:24'],
['He that is faithful in that which is least is faithful also in much.','Luke 16:10'],
['For unto whomsoever much is given, of him shall be much required.','Luke 12:48'],
['For where your treasure is, there will your heart be also.','Luke 12:34'],
['He that humbleth himself shall be exalted.','Luke 14:11'],
['For the Son of man is come to seek and to save that which was lost.','Luke 19:10'],
['In your patience possess ye your souls.','Luke 21:19'],
['In the beginning was the Word, and the Word was with God, and the Word was God.','John 1:1'],
['And the light shineth in darkness; and the darkness comprehended it not.','John 1:5'],
['He must increase, but I must decrease.','John 3:30'],
['My meat is to do the will of him that sent me, and to finish his work.','John 4:34'],
['I am the light of the world: he that followeth me shall not walk in darkness.','John 8:12'],
['I am come that they might have life, and that they might have it more abundantly.','John 10:10'],
['I am the good shepherd: the good shepherd giveth his life for the sheep.','John 10:11'],
['I am the resurrection, and the life.','John 11:25'],
['A new commandment I give unto you, That ye love one another.','John 13:34'],
['Let not your heart be troubled: ye believe in God, believe also in me.','John 14:1'],
['If ye love me, keep my commandments.','John 14:15'],
['I am the vine, ye are the branches... without me ye can do nothing.','John 15:5'],
['This is my commandment, That ye love one another, as I have loved you.','John 15:12'],
['Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit.','John 15:16'],
['Be of good cheer; I have overcome the world.','John 16:33'],
['It is more blessed to give than to receive.','Acts 20:35'],
['We ought to obey God rather than men.','Acts 5:29'],
['The just shall live by faith.','Romans 1:17'],
['Tribulation worketh patience; and patience, experience; and experience, hope.','Romans 5:3–4'],
['The love of God is shed abroad in our hearts by the Holy Ghost.','Romans 5:5'],
['To be spiritually minded is life and peace.','Romans 8:6'],
['In all these things we are more than conquerors through him that loved us.','Romans 8:37'],
['Present your bodies a living sacrifice, holy, acceptable unto God.','Romans 12:1'],
['Be not conformed to this world: but be ye transformed by the renewing of your mind.','Romans 12:2'],
['Be of the same mind one toward another.','Romans 12:16'],
['If it be possible, as much as lieth in you, live peaceably with all men.','Romans 12:18'],
['Love worketh no ill to his neighbour: therefore love is the fulfilling of the law.','Romans 13:10'],
['Let every man be fully persuaded in his own mind.','Romans 14:5'],
['Let every one of us please his neighbour for his good to edification.','Romans 15:2'],
['God is faithful, by whom ye were called unto the fellowship of his Son.','1 Corinthians 1:9'],
['Let every man take heed how he buildeth thereupon.','1 Corinthians 3:10'],
['Know ye not that ye are the temple of God?','1 Corinthians 3:16'],
['Moreover it is required in stewards, that a man be found faithful.','1 Corinthians 4:2'],
['All things are lawful unto me, but all things are not expedient.','1 Corinthians 6:12'],
['Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God.','1 Corinthians 10:31'],
['There are diversities of gifts, but the same Spirit.','1 Corinthians 12:4'],
['Charity suffereth long, and is kind.','1 Corinthians 13:4'],
['Charity never faileth.','1 Corinthians 13:8'],
['Let all things be done unto edifying.','1 Corinthians 14:26'],
['Thanks be to God, which giveth us the victory through our Lord Jesus Christ.','1 Corinthians 15:57'],
['Be ye stedfast, unmoveable, always abounding in the work of the Lord.','1 Corinthians 15:58'],
['Our sufficiency is of God.','2 Corinthians 3:5'],
['Where the Spirit of the Lord is, there is liberty.','2 Corinthians 3:17'],
['We are troubled on every side, yet not distressed.','2 Corinthians 4:8'],
['For our light affliction... worketh for us a far more exceeding and eternal weight of glory.','2 Corinthians 4:17'],
['If any man be in Christ, he is a new creature.','2 Corinthians 5:17'],
['God loveth a cheerful giver.','2 Corinthians 9:7'],
['He which soweth bountifully shall reap also bountifully.','2 Corinthians 9:6'],
['My grace is sufficient for thee.','2 Corinthians 12:9'],
['Bear ye one another’s burdens, and so fulfil the law of Christ.','Galatians 6:2'],
['As we have therefore opportunity, let us do good unto all men.','Galatians 6:10'],
['The fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.','Galatians 5:22'],
['Walk in the Spirit.','Galatians 5:16'],
['For by grace are ye saved through faith... it is the gift of God.','Ephesians 2:8'],
['For we are his workmanship, created in Christ Jesus unto good works.','Ephesians 2:10'],
['Endeavouring to keep the unity of the Spirit in the bond of peace.','Ephesians 4:3'],
['Speaking the truth in love.','Ephesians 4:15'],
['Walk in love, as Christ also hath loved us.','Ephesians 5:2'],
['Walk as children of light.','Ephesians 5:8'],
['Be strong in the Lord, and in the power of his might.','Ephesians 6:10'],
['Put on the whole armour of God.','Ephesians 6:11'],
['He which hath begun a good work in you will perform it until the day of Jesus Christ.','Philippians 1:6'],
['Let your moderation be known unto all men.','Philippians 4:5'],
['My God shall supply all your need according to his riches in glory by Christ Jesus.','Philippians 4:19'],
['Set your affection on things above, not on things on the earth.','Colossians 3:2'],
['Put on charity, which is the bond of perfectness.','Colossians 3:14'],
['Let the peace of God rule in your hearts.','Colossians 3:15'],
['Let the word of Christ dwell in you richly in all wisdom.','Colossians 3:16'],
['Walk in wisdom toward them that are without, redeeming the time.','Colossians 4:5'],
['Comfort yourselves together, and edify one another.','1 Thessalonians 5:11'],
['Prove all things; hold fast that which is good.','1 Thessalonians 5:21'],
['Faithful is he that calleth you, who also will do it.','1 Thessalonians 5:24'],
['God hath not called us unto uncleanness, but unto holiness.','1 Thessalonians 4:7'],
['Fight the good fight of faith.','1 Timothy 6:12'],
['Godliness with contentment is great gain.','1 Timothy 6:6'],
['Be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity.','1 Timothy 4:12'],
['Study to shew thyself approved unto God, a workman that needeth not to be ashamed.','2 Timothy 2:15'],
['Endure hardness, as a good soldier of Jesus Christ.','2 Timothy 2:3'],
['All scripture is given by inspiration of God, and is profitable.','2 Timothy 3:16'],
['I have fought a good fight, I have finished my course, I have kept the faith.','2 Timothy 4:7'],
['In all things shewing thyself a pattern of good works.','Titus 2:7'],
['Let us consider one another to provoke unto love and to good works.','Hebrews 10:24'],
['Let us hold fast the profession of our faith without wavering; for he is faithful that promised.','Hebrews 10:23'],
['Faith is the substance of things hoped for, the evidence of things not seen.','Hebrews 11:1'],
['Without faith it is impossible to please him.','Hebrews 11:6'],
['Jesus Christ the same yesterday, and to day, and for ever.','Hebrews 13:8'],
['Be not forgetful to entertain strangers.','Hebrews 13:2'],
['To do good and to communicate forget not.','Hebrews 13:16'],
['The trying of your faith worketh patience.','James 1:3'],
['Let patience have her perfect work.','James 1:4'],
['Be ye doers of the word, and not hearers only.','James 1:22'],
['The wisdom that is from above is first pure, then peaceable, gentle, and easy to be intreated.','James 3:17'],
['Draw nigh to God, and he will draw nigh to you.','James 4:8'],
['The effectual fervent prayer of a righteous man availeth much.','James 5:16'],
['Be ye holy in all manner of conversation.','1 Peter 1:15'],
['Honour all men. Love the brotherhood. Fear God.','1 Peter 2:17'],
['Christ also suffered for us, leaving us an example, that ye should follow his steps.','1 Peter 2:21'],
['Be ready always to give an answer... with meekness and fear.','1 Peter 3:15'],
['Use hospitality one to another without grudging.','1 Peter 4:9'],
['Be clothed with humility.','1 Peter 5:5'],
['The God of all grace... make you perfect, stablish, strengthen, settle you.','1 Peter 5:10'],
['Giving all diligence, add to your faith virtue; and to virtue knowledge.','2 Peter 1:5'],
['Grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ.','2 Peter 3:18'],
['If we walk in the light, as he is in the light, we have fellowship one with another.','1 John 1:7'],
['Let us not love in word, neither in tongue; but in deed and in truth.','1 John 3:18'],
['Perfect love casteth out fear.','1 John 4:18'],
['This is the victory that overcometh the world, even our faith.','1 John 5:4'],
['Beloved, follow not that which is evil, but that which is good.','3 John 1:11'],
['Keep yourselves in the love of God.','Jude 1:21'],
['Be thou faithful unto death, and I will give thee a crown of life.','Revelation 2:10'],
['Behold, I make all things new.','Revelation 21:5']
];
// Build a deterministic 365-day collection from the curated KJV/public-domain set.
const verses=Array.from({length:365},(_,i)=>baseVerses[i%baseVerses.length]);
const now=new Date();
const start=new Date(now.getFullYear(),0,0);const day=Math.floor((now-start)/86400000);
const verse=verses[(day-1+365)%365];
const track=document.getElementById('verseTrack'),shell=document.getElementById('verseShell'),bar=document.getElementById('verseBar'),panel=document.getElementById('versePanel'),close=document.getElementById('verseClose');
if(!track||!shell||!bar||!panel||!close)return;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const item=`<span class="verse-item"><span aria-hidden="true">▱</span><span class="verse-label">VERSE OF THE DAY</span><span class="verse-divider">|</span><span class="verse-copy">“${esc(verse[0])}”</span><span class="verse-ref">— ${esc(verse[1]).toUpperCase()}</span><span class="verse-star">✦</span></span>`;
track.innerHTML=item+item+item+item;
document.getElementById('verseFullText').textContent='“'+verse[0]+'”';document.getElementById('verseFullRef').textContent='— '+verse[1].toUpperCase();document.getElementById('verseAccessible').textContent='Verse of the Day: '+verse[0]+' — '+verse[1];
function setOpen(open){shell.classList.toggle('is-open',open);bar.setAttribute('aria-expanded',String(open));panel.setAttribute('aria-hidden',String(!open));}
bar.addEventListener('click',()=>setOpen(!shell.classList.contains('is-open')));close.addEventListener('click',e=>{e.stopPropagation();setOpen(false);bar.focus()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&shell.classList.contains('is-open'))setOpen(false)});
})();